### ISSUE TITLE
[bug] Toolbar icon click has no response 工具栏图标点击无效

### ISSUE THREAD

**Issue by hankeke303** [wflixu/RClick#12]
如题，在点击这个图标之后什么也没有发生。
As the title suggests, nothing happens after clicking this icon.

![](https://github.com/user-attachments/assets/fa583295-1c2c-418b-87cb-f4de325ee6c4)

APP Version: 1.3.1
OS: MacOS Sonoma 14.6.1

另外还有一个无伤大雅的 bug（也可能是 feature？）：在 APP 设置界面按 ⌘-W 无法关闭窗口，而是会关闭打开 APP 设置之前的窗口，虽然不是不能用，但是体验上会有些不太好。 
There is also an innocuous bug (or possibly a feature?): Pressing ⌘-W in the APP settings interface does not close this window but instead closes the window opened before, which, although not unusable, is somewhat less than ideal in terms of user experience.

**Comment by wflixu** [comment]
工具栏没有添加功能，之前没想到要做工具栏的菜单
