### ISSUE TITLE
大佬什么时候可以支持sequoia系统呀，新版本的系统没有了访达的插件管理，这个app用不了了

### ISSUE THREAD

**Issue by NoPKU** [wflixu/RClick#13]
大佬什么时候可以支持sequoia系统呀，新版本的系统没有了访达的插件管理，这个app用不了了

**Comment by wflixu** [comment]
sequoia系统 等下个月正式发布了会第一时间支持，在用的电脑不太方便升级Beta 版本的系统

**Comment by wflixu** [comment]
![image](https://github.com/user-attachments/assets/bd237add-2bbf-4395-bcfe-b835b600cac9)

可以试试论坛上的方法

**Comment by NoPKU** [comment]
感谢大佬

**Comment by wflixu** [comment]
macOS 15 确实有问题，先使用下面三个命令

```
# 查看插件列表 “-” 代表没有启用，“+” 代表已经启用
pluginkit  -mAD -p com.apple.FinderSync
#开启 插件
pluginkit -e "use" -i "cn.wflixu.RClick.FinderSyncExt"
# 关闭插件
pluginkit -e "ignore" -i "cn.wflixu.RClick.FinderSyncExt"

```

![image](https://github.com/user-attachments/assets/b62de651-b35e-475e-b7bc-90ed8ed58d1b)

**Comment by wflixu** [comment]
放弃sandbox，那样就无法提交到 apple mac store，现在的方案是做一个 非sandbox app，专门配置 macOS  15 的 Finder sync extension，不仅可以用作RClick，其他的app 的插件也能管理。 新的应用 FinderSyncer，已经发布，效果如下：

https://github.com/wflixu/FinderSyncer/releases

![image](https://github.com/user-attachments/assets/cf684f4b-2cd7-448d-b070-7732b456f347)
