### ISSUE TITLE
[feat] 自定义新建文件功能

### ISSUE THREAD

**Issue by ghost** [wflixu/RClick#18]
如题。目前支持的文件类型有 txt、md、json、docx、xlsx、pptx，但是在日常使用时有时候需要快速新建其他类型的文件，例如 py、css、js、sh 等。全部加进应用里不现实，因此希望增添一个自定义新建文件功能，例如可以让用户选择一个模板文件（template），然后在点击时根据这个模板文件新建一个文件，类似 `cp` 的操作；或者是自定义后缀名。相信这会给用户带来很大的方便。

此致。

**Comment by yoghurtlee-thu** [comment]
Hi there, just popping in to see if there's been any movement on this issue :)

**Comment by wflixu** [comment]
这个功能有稍微有点复杂，最近在做 Picasa，下周看看怎么实现的，

**Comment by wflixu** [comment]
#34

**Comment by chlorine3545** [comment]
Awesome Work :)

不过想问一下，custom icon 应该怎么操作呢？

**Comment by wflixu** [comment]
> Awesome Work :)
> 
> 不过想问一下，custom icon 应该怎么操作呢？

可以选择sf 符号，也可以选择一个 app 作为新建 文件类型的 图标，这个图标只出现在 RClick 文件类型列表中和 右键菜单中，文件的图标是 自己设置默认文件打开方式决定的，和RClick 无关
