### ISSUE TITLE
右键文件夹内空白外增加功能

### ISSUE THREAD

**Issue by Kurt-Shiwz** [wflixu/RClick#23]
1 “复制路径”，这里文件夹的路径
2 “打开此目录”，这里指用终端打开，我用的WezTerm，所以需要能指定终端app

![image](https://github.com/user-attachments/assets/057a173a-cdda-4e05-8edf-63f915ee7781)

**Comment by wflixu** [comment]
2 直接用 用webterm 打开不行嘛，

**Comment by Kurt-Shiwz** [comment]
> 2 直接用 用webterm 打开不行嘛，

1 可以，现在用“超级右键助手”就是这么用的。不过它可以右键当前目录的空白地方“拷贝当前目录地址”，不需要点在“文件”或者“文件夹”上“拷贝这个文件的目录地址”。
2 WezTerm我多数在本地用，webterm一般是公司的服务提供，不需要访问本地资源。（我看你回的webterm，这两个差一个字母 有可能你看错了）

**Comment by wflixu** [comment]
> > 2 直接用 用webterm 打开不行嘛，
> 
> 1 可以，现在用“超级右键助手”就是这么用的。不过它可以右键当前目录的空白地方“拷贝当前目录地址”，不需要点在“文件”或者“文件夹”上“拷贝这个文件的目录地址”。 2 WezTerm我多数在本地用，webterm一般是公司的服务提供，不需要访问本地资源。（我看你回的webterm，这两个差一个字母 有可能你看错了）

我 大错字了，WezTerm  这个需求不是很理解，你要打开文件编辑吗，目前如果用 终端打开，是打开目录，终端的当前路径是这这个目录， iTerm2 正常，

**Comment by Kurt-Shiwz** [comment]
> > > 2 直接用 用webterm 打开不行嘛，
> > 
> > 
> > 1 可以，现在用“超级右键助手”就是这么用的。不过它可以右键当前目录的空白地方“拷贝当前目录地址”，不需要点在“文件”或者“文件夹”上“拷贝这个文件的目录地址”。 2 WezTerm我多数在本地用，webterm一般是公司的服务提供，不需要访问本地资源。（我看你回的webterm，这两个差一个字母 有可能你看错了）
> 
> 我 打错字了，WezTerm 这个需求不是很理解，你要打开文件编辑吗，目前如果用 终端打开，是打开目录，终端的当前路径是这个目录， iTerm2 正常，

可能我描述的有问题，更准确的说是“调用WezTerm 并 cd到 当前这个目录”。之前一些简单的修改 我在终端进到当前目录后打开vim，用插件NERDTree列出文件列表后 定位文件然后打开、修改。
![image](https://github.com/user-attachments/assets/2ff22332-ae3b-4462-92e1-57fb5f883cf6)

**Comment by wflixu** [comment]
目前 ITerm2和macOS 自带的终端 都是这个行为， 在文件夹中点 用 iTerm2打开，就是cd 到当前文件夹下，wezterm 没有测试

**Comment by Kurt-Shiwz** [comment]
> 目前 ITerm2和macOS 自带的终端 都是这个行为， 在文件夹中点 用 iTerm2打开，就是cd 到当前文件夹下，wezterm 没有测试

1 iTerm2确实支持这个功能，之前没有把iTerm2加入到右键功能中，刚才只加了WezTerm
2 WezTerm不支持（这个终端用户应该也没那么多，可能没留这个接口都）
![image](https://github.com/user-attachments/assets/a2ae68fe-5155-4c6a-a8af-e95756a67fd3)
3 拷贝当前文件夹的路径（右键当前文件夹的空白处），这个功能有希望支持吗？

**Comment by wflixu** [comment]
> > > > 2 直接用 用webterm 打开不行嘛，
> > > 
> > > 
> > > 1 可以，现在用“超级右键助手”就是这么用的。不过它可以右键当前目录的空白地方“拷贝当前目录地址”，不需要点在“文件”或者“文件夹”上“拷贝这个文件的目录地址”。 2 WezTerm我多数在本地用，webterm一般是公司的服务提供，不需要访问本地资源。（我看你回的webterm，这两个差一个字母 有可能你看错了）
> > 
> > 
> > 我 打错字了，WezTerm 这个需求不是很理解，你要打开文件编辑吗，目前如果用 终端打开，是打开目录，终端的当前路径是这个目录， iTerm2 正常，
> 
> 可能我描述的有问题，更准确的说是“调用WezTerm 并 cd到 当前这个目录”。之前一些简单的修改 我在终端进到当前目录后打开vim，用插件NERDTree列出文件列表后 定位文件然后打开、修改。 ![image](https://private-user-images.githubusercontent.com/7554917/367782962-2ff22332-ae3b-4462-92e1-57fb5f883cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTYwNzksIm5iZiI6MTcyNjQ5NTc3OSwicGF0aCI6Ii83NTU0OTE3LzM2Nzc4Mjk2Mi0yZmYyMjMzMi1hZTNiLTQ0NjItOTJlMS01N2ZiNWY4ODNjZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTQwOTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ1YTBmNGMzMGZlMTkyMzkyMjllNGNmM2ZjZjEyZjUwZDg3NTBhOWFhOGEwMGRjMDhiNjlmOGY5ZTU2NzIyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7hXIC8vMivnXJ8oTi049iRuGLIvxlDaw28QeFW6_BYc)

测试是不正常，但感觉好像是 wezterm 的问题，
![image](https://github.com/user-attachments/assets/f8ab1522-55c5-4223-a300-2e887d351fa5)

**Comment by wflixu** [comment]
> 是 wezterm 的问题

可以，下一个版本加，之前已经发现了这个缺失

**Comment by Kurt-Shiwz** [comment]
> > > > > 2 直接用 用webterm 打开不行嘛，
> > > > 
> > > > 
> > > > 1 可以，现在用“超级右键助手”就是这么用的。不过它可以右键当前目录的空白地方“拷贝当前目录地址”，不需要点在“文件”或者“文件夹”上“拷贝这个文件的目录地址”。 2 WezTerm我多数在本地用，webterm一般是公司的服务提供，不需要访问本地资源。（我看你回的webterm，这两个差一个字母 有可能你看错了）
> > > 
> > > 
> > > 我 打错字了，WezTerm 这个需求不是很理解，你要打开文件编辑吗，目前如果用 终端打开，是打开目录，终端的当前路径是这个目录， iTerm2 正常，
> > 
> > 
> > 可能我描述的有问题，更准确的说是“调用WezTerm 并 cd到 当前这个目录”。之前一些简单的修改 我在终端进到当前目录后打开vim，用插件NERDTree列出文件列表后 定位文件然后打开、修改。 ![image](https://private-user-images.githubusercontent.com/7554917/367782962-2ff22332-ae3b-4462-92e1-57fb5f883cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTYwNzksIm5iZiI6MTcyNjQ5NTc3OSwicGF0aCI6Ii83NTU0OTE3LzM2Nzc4Mjk2Mi0yZmYyMjMzMi1hZTNiLTQ0NjItOTJlMS01N2ZiNWY4ODNjZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTQwOTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ1YTBmNGMzMGZlMTkyMzkyMjllNGNmM2ZjZjEyZjUwZDg3NTBhOWFhOGEwMGRjMDhiNjlmOGY5ZTU2NzIyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7hXIC8vMivnXJ8oTi049iRuGLIvxlDaw28QeFW6_BYc)
> 
> 测试是不正常，但感觉好像是 wezterm 的问题， ![image](https://private-user-images.githubusercontent.com/37231473/367791761-f8ab1522-55c5-4223-a300-2e887d351fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTcyOTgsIm5iZiI6MTcyNjY1Njk5OCwicGF0aCI6Ii8zNzIzMTQ3My8zNjc3OTE3NjEtZjhhYjE1MjItNTVjNS00MjIzLWEzMDAtMmU4ODdkMzUxZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEwNTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZGViZTE2ZWVjOTZkZTczNGM2NGE2MDkzMTgwYmNjZmI2NTAwY2Q3ZmI3ODY4ZmE3ZWU5ODFiYWE2MGUyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AY36FZNtZ_0tHxdsAqBlXW1yozlrRmk3avx45RRpYFU)

刚才在README.md中看到相似项中有提到 `https://github.com/Ji4n1ng/OpenInTerminal`，看到它功能描述中提到支持WezTerm，试了一下命令是可以的。`open -na wezterm --args start --cwd /Users/root`。
RClick会考虑支持一下吗？


关键代码（没看过swift，感觉应该是这里）
```
    /// get `open` command
    public func getOpenCommand(_ app: App, escapeCount: Int = 1) -> String {
        if SupportedApps.is(app, is: .alacritty) {
            return "open -na Alacritty --args --working-directory"
        } else if SupportedApps.is(app, is: .kitty) {
            return "open -na kitty --args --single-instance --instance-group 1 --directory"
        } else if SupportedApps.is(app, is: .wezterm) {
            return "open -na wezterm --args start --cwd"
        } else if SupportedApps.is(app, is: .tabby) {
            return "open -na tabby --args --directory"
        } else {
            return "open -a \(app.name.nameSpaceEscaped(escapeCount))"
        }
    }
```

![image](https://github.com/user-attachments/assets/fbd52394-ba44-4a79-b23d-7d6686ef52ae)

**Comment by wflixu** [comment]
应该可以，按你提供的代码把路径加入打开参数应该就可以了

**Comment by Kurt-Shiwz** [comment]
> > 是 wezterm 的问题
> 
> 可以，拷贝当前文件夹的路径下一个版本加，之前已经发现了这个缺失

问一下 近期有发版安排吗

**Comment by wflixu** [comment]
之前想着 v2 重构一下代码，附加修改这个参数少的问题，现在v2 因为macOS 15搁置，计划周末或下周出 1.5版本的修复这个问题

**Comment by wflixu** [comment]
目前能打开wezterm，但是目录参数传入，无效，每次都是home目录
