### ISSUE TITLE
应用程序“RClick”没有权限打开“桌面”

### ISSUE THREAD

**Issue by Sherlockedb** [wflixu/RClick#24]
已经授权的文件夹：/Users/xxx
桌面路径是：/User/xxx/Desktop

在桌面右键-用VSCode/终端/iTerm打开，然后报错：应用程序“RClick”没有权限打开“桌面”

![没有权限打开“桌面”](https://github.com/user-attachments/assets/f3fc6384-4241-4ca3-a323-605c8e508a0b)

**Comment by wflixu** [comment]
重启一下，或删除授权文件夹，重新添加一下试试
