### ISSUE TITLE
有些APP启动参数不是标准化的，建议可以让用户自己设置启动参数

### ISSUE THREAD

**Issue by 87074139** [wflixu/RClick#25]
比如右键菜单可以支持直接shell脚本可以让用户自定义非标准启动方式
创建文件也可以自定义就好了
补充一点有些APP名字会撑开菜单的宽度建议可以自定义菜单的启动名称

**Comment by wflixu** [comment]
app 执行shell 在sandbox 中很繁琐，将来发一个非sandbox 版本添加，创建文件以后的版本会添加自定义，自定义菜单名字以以后的版本添加

**Comment by wflixu** [comment]
#33
