### ISSUE TITLE
sequoia添加扩展的时候没有看到RClick的选项

### ISSUE THREAD

**Issue by travisbikkle** [wflixu/RClick#26]
<img width="470" alt="image" src="https://github.com/user-attachments/assets/d29c155f-59eb-4a06-a0b9-c624b2931436">

是哪里设置有问题吗

**Comment by wflixu** [comment]
sequoia 去掉 了 Finder sync extension  的配置，使用这个专门配置 的app ，https://github.com/wflixu/FinderSyncer

**Comment by LeeSurer** [comment]
> sequoia 去掉了 Finder 同步扩展的配置，使用这个专门配置的应用程序， https: [//github.com/wflixu/FinderSyncer](https://github.com/wflixu/FinderSyncer)

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/19b6d150-3ac1-48f9-92ef-5396eb655585">
FinderSyncer列表里没有RClick

**Comment by SYYatSEU** [comment]
遇到了相同的问题，不管有没有打开RClick，FinderSyncer列表中都没有

**Comment by wflixu** [comment]
系统版本说一下

**Comment by SYYatSEU** [comment]
sequoia 15.0.1

**Comment by fzrbcjg** [comment]
同问，系统sequoia 15.0.1

**Comment by wflixu** [comment]
https://developer.apple.com/forums/thread/756711?answerId=812625022#812625022

![image](https://github.com/user-attachments/assets/b758dee1-8bc4-4fb4-99a9-de85cd8152f0)


macos 15.2 将修复设置

**Comment by fzrbcjg** [comment]
谢谢🙏大佬，感谢

**Comment by elijahxb** [comment]
<img width="1530" alt="image" src="https://github.com/user-attachments/assets/d5000064-937a-427c-955a-023a1e98969e">


用了FinderSync，还是看不到Rclick

**Comment by wflixu** [comment]
我在 macOS 15.1上测试的正常
![image](https://github.com/user-attachments/assets/a7f7d9d3-f603-4faa-8fea-bd7b55888265)

**Comment by wflixu** [comment]
试试另一个开发者的 工具 https://zigz.ag/FinderSyncer/

![image](https://github.com/user-attachments/assets/45f8a1c6-b4ea-4139-b1aa-415c6031bf80)

**Comment by elijahxb** [comment]
> 我在 macOS 15.1上测试的正常 ![image](https://private-user-images.githubusercontent.com/37231473/386042665-a7f7d9d3-f603-4faa-8fea-bd7b55888265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTg0NTMsIm5iZiI6MTczMTU1ODE1MywicGF0aCI6Ii8zNzIzMTQ3My8zODYwNDI2NjUtYTdmN2Q5ZDMtZjYwMy00ZmFhLThmZWEtYmQ3YjU1ODg4MjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNDBkNTYwOWJkYWUwODhkMTVhN2Y4OGVjZTY2YjFkZTAzYTA3ZGVlOWZiZmNkMTc2MzcyODRhOGU4NmNhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X15SbBwiYSD-qEkHyLYfpsht2Dn6htxNzj8J21Us1hs)

那可能是芯片原因了
<img width="269" alt="image" src="https://github.com/user-attachments/assets/bc88af20-1460-4a1f-b888-61e325c7c45e">

**Comment by wflixu** [comment]
> https://zigz.ag/FinderSyncer/

用这个试试

**Comment by elijahxb** [comment]
> 试试另一个开发者的 工具 https://zigz.ag/FinderSyncer/
> 
> ![image](https://private-user-images.githubusercontent.com/37231473/386042946-45f8a1c6-b4ea-4139-b1aa-415c6031bf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTg2MzEsIm5iZiI6MTczMTU1ODMzMSwicGF0aCI6Ii8zNzIzMTQ3My8zODYwNDI5NDYtNDVmOGExYzYtYjRlYS00MTM5LWIxYWEtNDE1YzYwMzFiZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NWU3ZTY5NzM1ZTkyYzdkYWNiZDA0MWNkOTJhYmUzYzQ3NTQ2YWY0Y2YyNWMzZWRhM2JkYTMzYTkyYjhmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pwynfgGJKbEq3kk9AZ1yM_139FHvBP2zfLdvYEUE1xw)

可以了，intel芯片的这个可行

**Comment by wflixu** [comment]
> > 试试另一个开发者的 工具 https://zigz.ag/FinderSyncer/
> > ![image](https://private-user-images.githubusercontent.com/37231473/386042946-45f8a1c6-b4ea-4139-b1aa-415c6031bf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTg2MzEsIm5iZiI6MTczMTU1ODMzMSwicGF0aCI6Ii8zNzIzMTQ3My8zODYwNDI5NDYtNDVmOGExYzYtYjRlYS00MTM5LWIxYWEtNDE1YzYwMzFiZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NWU3ZTY5NzM1ZTkyYzdkYWNiZDA0MWNkOTJhYmUzYzQ3NTQ2YWY0Y2YyNWMzZWRhM2JkYTMzYTkyYjhmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pwynfgGJKbEq3kk9AZ1yM_139FHvBP2zfLdvYEUE1xw)
> 
> 可以了，intel芯片的这个可行

那应该是 Findersyncer打包的时候没有包含 intel x86 架构

**Comment by Northcity-Gu** [comment]
终端执行这个就有了  pluginkit -e "use" -i cn.wflixu.RClick.FinderSyncExt

**Comment by zjt003** [comment]
15.1.1 使用 https://zigz.ag/FinderSyncer 将RClick扩展打开 右键还是没有RClick的选项
![图片](https://github.com/user-attachments/assets/15578960-afc6-4e70-a8ba-420df3d8a78f)

**Comment by wflixu** [comment]
> 15.1.1 使用 https://zigz.ag/FinderSyncer 将RClick扩展打开 右键还是没有RClick的选项 ![图片](https://private-user-images.githubusercontent.com/185868737/389198599-15578960-afc6-4e70-a8ba-420df3d8a78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzAwNTIsIm5iZiI6MTczMjM2OTc1MiwicGF0aCI6Ii8xODU4Njg3MzcvMzg5MTk4NTk5LTE1NTc4OTYwLWFmYzYtNGU3MC1hOGJhLTQyMGRmM2Q4YTc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzQ5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTgzZjYwOTI3MmEzMmU0NzIxYTAzMjIwNjdjYTUwZjM2YmJiMjI3MThlZTNiOGEwMmNiMzZlMmUwZWJhNTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nYKso94WpwZ0Fn58psyzxxOiqJOXXxKtEn7Rj04EDS8)

添加授权文件夹，在文件夹内才能 显示右键

**Comment by zjt003** [comment]
有添加授权文件夹

**Comment by zjt003** [comment]
> > 15.1.1 使用 https://zigz.ag/FinderSyncer 将RClick扩展打开 右键还是没有RClick的选项 ![undefined](https://private-user-images.githubusercontent.com/185868737/389198599-15578960-afc6-4e70-a8ba-420df3d8a78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzAwNTIsIm5iZiI6MTczMjM2OTc1MiwicGF0aCI6Ii8xODU4Njg3MzcvMzg5MTk4NTk5LTE1NTc4OTYwLWFmYzYtNGU3MC1hOGJhLTQyMGRmM2Q4YTc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzQ5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTgzZjYwOTI3MmEzMmU0NzIxYTAzMjIwNjdjYTUwZjM2YmJiMjI3MThlZTNiOGEwMmNiMzZlMmUwZWJhNTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nYKso94WpwZ0Fn58psyzxxOiqJOXXxKtEn7Rj04EDS8)
> 
> 添加授权文件夹，在文件夹内才能 显示右键

大佬，后续有把RClick放到homebrew的想法吗？

**Comment by wflixu** [comment]
macos 15.2  Finder sync 拓展设置已经回来了

![image](https://github.com/user-attachments/assets/da227ff9-2707-44dd-acd1-074af2d3ddae)
