### ISSUE TITLE
The application does not have permission to open the folder

### ISSUE THREAD

**Issue by wulide** [wflixu/RClick#27]
![image](https://github.com/user-attachments/assets/34a29613-ed12-405b-a9c1-ec050eeaf432)

**Comment by wflixu** [comment]
What is your system version number

**Comment by wulide** [comment]
> What is your system version number. macOS 15 ?

sonoma 14.4.1

**Comment by wflixu** [comment]
把授权文件夹删除后，重新添加一下，可能是失效了，打开的文件夹必须包含在 授权文件夹中
