### ISSUE TITLE
希望添加功能，可以在桌面或当前目录下右键空位置，可以拷贝当前路径。

### ISSUE THREAD

**Issue by h0ny** [wflixu/RClick#36]
下图这种情况下，不能拷贝当前路径，必须要选中某个目录或文件才行。

<img width="476" alt="image" src="https://github.com/user-attachments/assets/e38fc079-63eb-4253-83e6-faf538fdf7ad">

**Comment by wflixu** [comment]
请下载最新版本，1.4.5之后已经可以
