### ISSUE TITLE
[bug] 如果在“桌面”和“文稿”里开启了iCloud同步，则在“桌面”、“文稿”文件夹中右键，显示的菜单失效。

### ISSUE THREAD

**Issue by HackwoodL** [wflixu/RClick#37]
bug，如果在“桌面”和“文稿”里开启了iCloud同步，则在“桌面”、“文稿”文件夹中右键，显示的菜单失效。

m1笔记本，系统是15.1.1 (24B91)

顺便想再问个不重要的小问题，每次授权目录只能手动添加四个目录/System /Applications /Users /Library，想请问一下有没有直接添加根目录的方法。

**Comment by wflixu** [comment]
可以直接根目录

![image](https://github.com/user-attachments/assets/a300ccb2-7430-401b-be5d-13d65fa198ac)


![image](https://github.com/user-attachments/assets/ed873016-baa7-4185-aa47-e3d4f4f7cd74)

**Comment by wflixu** [comment]
感谢反馈，

实际测试，同步文件夹中  toolbar 还可以用，



![image](https://github.com/user-attachments/assets/fce817be-8f89-4fa9-9705-bbbea3d1155a)

目前还没有解决办法，
