### ISSUE TITLE
重启电脑后，文件授权功能失效，无法新建文件。

### ISSUE THREAD

**Issue by fzrbcjg** [wflixu/RClick#42]
见字问好！大佬！我在使用过程重，重启电脑后，文件授权功能失效，无法新建文件。是通用问题还是我个人问题？谢谢！

**Comment by wflixu** [comment]
文件夹是不是中文的？

**Comment by fzrbcjg** [comment]
就是在桌面新建文件，授权文件夹是全部
<img width="828" alt="iShot_2024-12-18_19 04 11" src="https://github.com/user-attachments/assets/ab154467-d6c9-4dc4-b871-92eac20cf959" />

**Comment by fzrbcjg** [comment]
重启后就向这样创建文件，就没有任何反应，需要重新给授权，然后就可以创建文件了
![1734519969504](https://github.com/user-attachments/assets/8b516af9-5378-4020-b3e9-a6058769b2ba)

**Comment by wflixu** [comment]
是有这个问题

**Comment by fzrbcjg** [comment]
那辛苦大佬  看看是否有办法解决，谢谢
