### ISSUE TITLE
新建xlsx文件格式问题

### ISSUE THREAD

**Issue by yhhe2004** [wflixu/RClick#44]
右键新建xlsx文件时无法直接使用Excel打开，报错Excel cannot open the file 'Untitled.xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.

macOS 15.2，Microsoft Office 2024，doc和ppt没有问题

**Comment by wflixu** [comment]
本地测试是这样的，

**Comment by wflixu** [comment]
v1.5.2 已经修复该问题
