### ISSUE TITLE
OS12.4 处理器 Intel 无法使用

### ISSUE THREAD

**Issue by kewab** [wflixu/RClick#7]
系统版本：12.4
处理器：2 GHz 四核Intel Core i5

**Comment by wflixu** [comment]
个人练手项目，没有能力适配低版本，目前最低适配14.0，感谢关注，以后熟练了可能会适配 macOS 12.x

**Comment by wflixu** [comment]
代码中有用 Observation，Observation 最低支持  macOS 14.0+
